### ISSUE TITLE
Indicator does not show on Ubuntu 14.04/16.04

### ISSUE THREAD

**Issue by tominglis** [eliostvs/tomate-indicator-plugin#3] opened 2016-02-23 16:54 UTC
I just installed tomate 0.5 and this plugin, but the indicator does not show in the indicator bar for me on Ubuntu 14.04.

It used to show with the old ppa version, 0.3.1.

**Comment by eliostvs** [comment] 2016-02-26 22:18
Hi. The plugin shows the progress of the session in the indicator area only when the timer is running and you close the window. What happen when you try to close the window in this situation? It disappears or minimizes?

**Comment by rogerkk** [comment] 2016-05-21 07:26
I guess this issue is a duplicate of https://github.com/eliostvs/tomate-gtk/issues/5, but that this is the more correct place for it, so I'm adding a comment here as well:

FWIW, I have the same problem in Ubuntu 16.04.

Wonder if this has something to do with Ubuntu's handling of the system tray? See for example this post: https://bugs.launchpad.net/ayatana-design/+bug/974480. Not sure if this means that Tomate would need to support some kind of application indicator system that Unity offers.

To answer your question, @eliostvs, I don't ever see the indicator, no matter if the timer is running or not.

Here are my plugin versions:

| test | version |
| --- | --- |
| tomate-gtk | 0.6.0 |
| tomate-alarm-plugin | 0.6.0 |
| tomate-indicator-plugin | 0.5.0 |
| tomate-launcher-plugin | 0.6.0 |
| tomate-notify-plugin | 0.7.0 |
| tomate-statusicon-plugin | 0.3.0 |

**Comment by rogerkk** [comment] 2016-05-21 07:30
Oh, and since I can't find any other way of contacting you, is there anywhere I can donate? Your software is saving my focus every day, I'd like to give a little bit back.

**Comment by eliostvs** [comment] 2016-05-21 15:22
Hi. I did a new release of the tomate-indicator-plugin (0.7.0). I will treat this problem in the [tomate-indicator-plugin issue page](https://github.com/eliostvs/tomate-indicator-plugin/issues/3). Could you try again and write the result there? Thank you.

**Comment by eliostvs** [comment] 2016-05-21 15:51
Hi. I did a new release on last Friday (0.7.0), it fixes the initial icon. I did some tests with the Ubuntu 16.04 in a VM (qemu) and it worked. Could you try again? Thanks.

**Comment by rogerkk** [comment] 2016-05-21 22:26
Oh, indeed that fixes it!

Sorry for not checking what was the latest released version, I just did an apt update & upgrade and didn't get that version. Bit of a brain fart on my part there.

As for the other question, which went unanswered: You don't accept donations? :/

**Comment by eliostvs** [comment] 2016-05-24 01:15
Frankly, I've never thought on that. For now it is enough for me to know that there are people who use and like Tomate. Thanks!

**Closed as completed by eliostvs** 2016-05-24 01:15 UTC
